builds:
  -
    env:
     - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
archives:
  -
   id: outflux 
   replacements:
     darwin: macOS
     linux: Linux
     windows: Windows
     386: i386
     amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "outflux_{{ .Tag }}"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
